Hisab.UI/Pages/App/Events/AddContributionTransaction.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Hisab.BL;
using Hisab.Common.BO;
using Hisab.Dapper.Identity;
using Hisab.UI.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using NToastNotify;

namespace Hisab.UI
{
    [Authorize(Roles = "App User, Admin")]
    public class AddContributionTransactionModel : PageModel
    {
        private IEventManager _eventManager;
        private UserManager<ApplicationUser> _userManager;
        private IEventTransactionManager _transactionManager;
        //private IToastNotification _toastNotification;

        [BindProperty]
        public ContributeVM ContributeVM { get; set; }

        public AddContributionTransactionModel(IEventManager eventManager, UserManager<ApplicationUser> userManager
                , IEventTransactionManager transactionManager)
        {
            _eventManager = eventManager;
            _userManager = userManager;
            _transactionManager = transactionManager;
            //_toastNotification = toastNotification;


        }
        public void OnGet(Guid Id)
        {
            

            
        }

        public async Task<IActionResult> OnGetToFriend(Guid Id)
        {
            ContributeVM = new ContributeVM();


                var user = await _userManager.FindByNameAsync(User.Identity.Name);
                var eve = await _eventManager.GetEventById(Id);

                ContributeVM.NickName = user.NickName;
                ContributeVM.UserId = user.Id;
                ContributeVM.TransactionDate = DateTime.Now;
                ContributeVM.EventId = Id;

                foreach(var friend in eve.Friends)
                {
                    if(friend.UserId != user.Id)
                    {
                        ContributeVM.Friends.Add(new EventFriendVm()
                        {
                            UserId = friend.UserId,
                            Name = friend.NickName

                        });
                    }
                }

            this.ViewData.Add("EventTitle", eve.EventName);

            return Page();
        }

        public async Task<IActionResult> OnPost()
        {
            
            if(!ModelState.IsValid)
            {
                return Page();
            }
            
            var newTrans = new NewTransactionBO();

            

            if(ContributeVM.PaidToFriendUserId != null)
            {
                // Contribute to Friend
                newTrans.EventId = ContributeVM.EventId;
                newTrans.CreatedByUserId = ContributeVM.UserId;
                newTrans.PaidByUserId = ContributeVM.UserId;
                newTrans.TotalAmount = ContributeVM.Amount;
                newTrans.TransactionDate = ContributeVM.TransactionDate;
                newTrans.Description = ContributeVM.Description;
                newTrans.PaidToFriendUserId = ContributeVM.PaidToFriendUserId.Value;

                var result = await _transactionManager.CreateContributeToFriend(newTrans);
                if (result)
                {
                    //_toastNotification.AddSuccessToastMessage($"The Amount of {ContributeVM.Amount} is lent to your friend.");

                    return RedirectToPage("Dashboard", new { id = ContributeVM.EventId });
                }
            }

            return Page();
        }
    }
}

Hisab.UI/Pages/App/Events/EventFriends.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Hisab.AWS;
using Hisab.BL;
using Hisab.Common.BO;
using Hisab.Dapper.Identity;
using Hisab.UI.Services;
using Hisab.UI.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;


namespace Hisab.UI
{
    [Authorize(Roles = "App User, Admin")]
    public class EventFriendsModel : PageModel
    {
        [BindProperty]
        public InviteFriendVm NewFriend { get; set; }

        public string InviteFriendMessage { get; set; }

        public List<string> InviteFriendMessages { get; set; }


        private IEventInviteManager _eventInviteManager { get; set; }
        private UserManager<ApplicationUser> _userManager { get; set; }

        private IEventManager _eventManager;
        private IEmailService _emailService;

        public List<UserEventInviteVM> PendingRequests { get; set; }
        
        [BindProperty]
        public List<InviteApplicationUserVM> RecommendedFriends { get; set; }


        public EventFriendsModel(IEventInviteManager eventInviteManager, UserManager<ApplicationUser> userManager, IEventManager eventManager, IEmailService emailService)
        {
            _eventInviteManager = eventInviteManager;
            _userManager = userManager;
            _eventManager = eventManager;
            _emailService = emailService;

            PendingRequests = new List<UserEventInviteVM>();
            RecommendedFriends = new List<InviteApplicationUserVM>();
            InviteFriendMessages = new List<string>();
        }
        public async Task<IActionResult> OnGet(Guid Id)
        {
            NewFriend = new InviteFriendVm();
            NewFriend.EventId = Id;

            
            var eve = await _eventManager.GetEventById(Id);
            this.ViewData.Add("EventTitle", eve.EventName);
            this.ViewData.Add("EventId", eve.Id);

            if (await _eventManager.CheckEventAccess(eve, User.Identity.Name))
            {
                //Get loggedin user
                var user = await _userManager.FindByNameAsync(User.Identity.Name);

                await LoadPendingRequest(NewFriend.EventId);

                await LoadRecommendedFriends(user.Id, NewFriend.EventId);

                return Page();
            }

            throw new UnauthorizedAccessException();

        }

        private async Task LoadPendingRequest(Guid Id)
        {
            //Get Pending friend requests
            var pendingRequests = await _eventInviteManager.GetPendingInvites(Id);

            foreach (var pendingRequest in pendingRequests)
            {
                PendingRequests.Add(new UserEventInviteVM()
                {
                    EventId = pendingRequest.EventId,
                    InviteStatus = pendingRequest.InviteStatus,
                    UserId = pendingRequest.UserId,
                    NickName = pendingRequest.NickName,
                    Avatar = HisabImageManager.GetAvatar(pendingRequest.AvatarId)
                });
            }
        }

        private async Task LoadRecommendedFriends(Guid userId, Guid eventId)
        {
            //Get recommended friends
            var recommendedFriends = await _eventInviteManager.GetRecommendedFriends(userId, eventId);

            foreach (var friend in recommendedFriends)
            {
                if(RecommendedFriends.FirstOrDefault(x => x.Id == friend.Id) == null)
                {
                    RecommendedFriends.Add(new InviteApplicationUserVM()
                    {
                        Id = friend.Id,
                        NickName = friend.NickName,
                        UserName = friend.Email,
                        Avatar = HisabImageManager.GetAvatar((AvatarEnum)friend.AvatarId),
                        Checked = false,
                        EventId = eventId
                    });
                }
                
                
            }
        }

        public async Task<IActionResult> OnPost()
        {
            if(ModelState.IsValid)
            {
                var fromUser = await _userManager.FindByNameAsync(User.Identity.Name);
                var result = await _eventInviteManager.InviteFriend(NewFriend.EventId, NewFriend.FriendEmail, fromUser.NickName);

                if(result.Success)
                {
                    InviteFriendMessage = result.Messge;
                                
                   
                }
                else
                {
                    ModelState.AddModelError("", result.Messge);
                }

            }

            //Get loggedin user
            var user = await _userManager.FindByNameAsync(User.Identity.Name);

            await LoadPendingRequest(NewFriend.EventId);

            await LoadRecommendedFriends(user.Id, NewFriend.EventId);

            return Page();
        }

        public async Task<IActionResult> OnPostSendInvites()
        {
            var invites = new List<NewInviteBO>();
            var fromUser = await _userManager.FindByNameAsync(User.Identity.Name);

            foreach (var friend in RecommendedFriends)
            {
                if(friend.Checked)
                {
                    invites.Add(new NewInviteBO() { EventId = friend.EventId, UserEmail = friend.UserName, LoggedInUser = fromUser.NickName });
                    NewFriend.EventId = friend.EventId; // eventId is going to be same
                }
            }

            if (invites.Count > 0)
            {
                var response = await _eventInviteManager.InviteFriends(invites);

                foreach (var r in response)
                {
                    InviteFriendMessages.Add(r.Messge);
                }
           
            }
            else
                InviteFriendMessages.Add("You must select a friend to add");


            await LoadPendingRequest(NewFriend.EventId);
            return Page();
        }
    }
}

Hisab.UI/Pages/App/Events/EventSettings.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Hisab.BL;
using Hisab.Common.BO;
using Hisab.UI.Extensions;
using Hisab.UI.Services;
using Hisab.UI.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;


namespace Hisab.UI
{
    [Authorize(Roles = "App User, Admin")]
    public class EventSettingsModel : PageModel
    {
        [BindProperty(SupportsGet =true)]
        public EventSettingsVM SettingsVM { get; set; }

        public string EventSettingMessage { get; set; }

        private IEventManager _eventManager;

        public EventSettingsModel(IEventManager eventManager)
        {
            _eventManager = eventManager;
        }

        public async Task<IActionResult> OnGet(Guid Id)
        {

            SettingsVM = new EventSettingsVM();

            var eve = await _eventManager.GetEventById(Id);
            
            if(await _eventManager.CheckEventAccess(eve,User.Identity.Name))
            {
                SettingsVM.EventName = eve.EventName;
                SettingsVM.SelectedEventImage = eve.EventPicId;
                SettingsVM.EventId = eve.Id;
                SettingsVM.SelectedCurrency = eve.CurrencyCode;

                foreach (var cur in Currency.GetAll())
                {
                    SettingsVM.CountryCurrency.Add(new CurrencyVM() { Code = cur.Key, Name = cur.Value });
                }

                foreach (var f in eve.Friends)
                {
                    //only load event friends
                    if (f.EventFriendStatus == EventFriendStatus.EventFriend)
                    {
                        SettingsVM.Friends.Add(new EventFriendVm()
                        {
                            EventId = f.EventId,
                            UserId = f.UserId,
                            Email = f.Email,
                            Name = f.NickName,
                            Status = f.EventFriendStatus.GetDescription(),
                            EventFriendStatus = f.EventFriendStatus,
                            IsFriendActive = f.IsFriendActive,
                            Avatar = HisabImageManager.GetAvatar(f.Avatar)
                        });

                    }

                }
                this.ViewData.Add("EventTitle", eve.EventName);
                return Page();
            }

            throw new UnauthorizedAccessException();
        }

        

        public async Task<IActionResult> OnPostEventSettings()
        {
            if (ModelState.IsValid)
            {
                var settingsBo = new EventSettingsBO()
                {
                    EventId = SettingsVM.EventId,
                    EventName = SettingsVM.EventName,
                    SelectedEventImage = SettingsVM.SelectedEventImage,
                    SelectedCurrency = SettingsVM.SelectedCurrency

                };
                foreach(var f in SettingsVM.Friends)
                {
                   
                        settingsBo.Friends.Add(new EventFriendBO()
                        { UserId = f.UserId, EventId = SettingsVM.EventId, EventFriendStatus = f.EventFriendStatus, IsFriendActive = f.IsFriendActive });
                    
                        
                                      
                }



                var result = await _eventManager.UpdateEvenSettings(settingsBo);

                if (result)
                {
                    EventSettingMessage = "Event settings updated sucessfully.";
                    foreach (var cur in Currency.GetAll())
                    {
                        SettingsVM.CountryCurrency.Add(new CurrencyVM() { Code = cur.Key, Name = cur.Value });
                    }

                }
                else
                {
                    ModelState.AddModelError("", "Error updating event settings");
                }
            }

            return Page();
        }

        public async Task<IActionResult> OnPostArchieveEvent()
        {
           var result = await _eventManager.ArchieveEvent(SettingsVM.EventId);

            if(result)
            {
                return RedirectToPage("/App/Events");
            }
            else
            {
                EventSettingMessage = "Couldnt archieve event";
            }

            return Page();
        }
    }
}

Hisab.UI/Pages/App/Events/TransactionDetails.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Hisab.UI
{
    public class TransactionDetailsModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

Hisab.UI/Pages/App/Events/AddContributionTransaction.cshtml
@page "/app/events/{id}/AddContributionTransaction"
@model Hisab.UI.AddContributionTransactionModel
@{
    ViewData["Title"] = "ContributionTransactionDetails";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<div style="float:left; margin:10px">
    <h2>Add Contribution</h2>
</div>
<div style="float:right; margin:10px" class="pageButton">
    <a asp-page="/app/events/dashboard" asp-route-id="@Model.ContributeVM.EventId"><i class="fa fa-undo-alt"></i> Back </a>
</div>

<div class="clearfix"></div>

<div class="pageForm">


    <form method="post">
        @Html.HiddenFor(x => x.ContributeVM.EventId)
        <div class="form-group row">
            <label for="contributionTitle" class="col-sm-2 col-form-label">Title:</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" asp-for="@Model.ContributeVM.Description" placeholder="Deposit">
                <span asp-validation-for="@Model.ContributeVM.Description" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <label for="contributionDate" class="col-sm-2 col-form-label">Date:</label>
            <div class="col-sm-10">
                <input class="form-control" type="date" asp-for="@Model.ContributeVM.TransactionDate">
            </div>
        </div>
        <div class="form-group row">
            <label for="contributionAmount" class="col-sm-2 col-form-label">Amount:</label>
            <div class="col-sm-10">
                <input class="form-control" asp-for="@Model.ContributeVM.Amount">
                <span asp-validation-for="@Model.ContributeVM.Amount" class="text-danger"></span>
            </div>
        </div>


        <div id="equalSplitContent">
            <table class="table  table-striped table-sm">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">From</th>
                        <th scope="col"></th>
                        <th scope="col">To</th>
                    </tr>
                </thead>
                <tbody>

                    <tr>
                        <td>
                            @Model.ContributeVM.NickName
                            @Html.HiddenFor(x => x.ContributeVM.UserId)
                        </td>
                        <td>
                            =>
                        </td>
                        <td>
                            <select asp-for="@Model.ContributeVM.PaidToFriendUserId" asp-items="@(new SelectList(Model.ContributeVM.Friends,"UserId","Name"))">
                            </select>
                            



                        </td>
                    </tr>






                </tbody>


            </table>
        </div>



        <div class="row transactionFooter">
            <div class="col-11 col-xs-11 transactionButtons">

                <button><i class="fa fa-edit"></i> Save</button>

             
            </div>
        </div>


    </form>


</div>




@section scripts{
    <script src="~/node_modules/jquery-validation/dist/jquery.validate.min.js" asp-append-version="true"></script>
    <script src="~/node_modules/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.min.js" asp-append-version="true"></script>

}

Hisab.UI/Pages/App/Events/Dashboard.cshtml
@page "/app/events/{id}/dashboard"
@model Hisab.UI.DashboardModel
@{
    ViewData["Title"] = "Dashboard";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

    


    <div class="container">
        @Html.HiddenFor(x => x.Event.EventId)
        <div class="row">
            <p>Total event expenses: @Model.Event.CurrencySymbol<div id="AllexpenseContent" style="padding-top:10px"></div></p>
        </div>
        <div class="row">
            <div class="col-6 col-md-6 eventDashboardTiles">
                <div class="card ">
                    <div class="card-body">

                        <h5 class="card-text">My Expenses</h5>
                        <div id="expenseSpinner" class="spinner-border" role="status">
                            <span class="sr-only">Loading...</span>
                        </div>
                        <p></p>
                        <div id="expenseContent" class="card-title tileNumbers"></div>
                        <div class="tileNumbers">@Model.Event.CurrencySymbol</div>


                    </div>
                    <div class="card-footer tileFooter">
                        <a asp-page="/app/events/AddExpenseTransaction" asp-route-id="@Model.Event.EventId">
                            <i class="fa fa-plus-square"></i> Add Expense
                        </a>
                    </div>
                </div>
            </div>
            @*<div class="col-6 col-md-6 eventDashboardTiles ">
                <div class="card ">
                    <div class="card-body">
                        <h5 class="card-text">My Contributions</h5>
                        <div id="MyContributionsSpinner" class="spinner-border" role="status">
                            <span class="sr-only">Loading...</span>
                        </div>
                        <p></p>
                        <div id="MyContributionsContent" class="card-title tileNumbers"></div>
                        <div class="tileNumbers">@Model.Event.CurrencySymbol</div>

                    </div>
                    <div class="card-footer tileFooter">
                        <a asp-page="/app/events/AddContributionTransaction" asp-route-id="@Model.Event.EventId" asp-page-handler="ToFriend">
                            <i class="fa fa-wallet"></i> Lend money
                        </a>

                    </div>
                </div>
            </div>*@
        <div class="col-6 col-md-6">

            <div class="card">
                <div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel">
                    <div class="carousel-inner">
                        <div class="carousel-item active">

                            <div>
                                <p>
                                    Everyone chipping in money for future expenses?
                                </p>


                            </div>

                        </div>
                        <div class="carousel-item">

                            <div>
                                <p>
                                    Use this option for the money pool or to track money lent to a friend.
                                </p>



                            </div>

                        </div>


                    </div>

                </div>
                <div class="tileFooter">
                    <a asp-page="/app/events/AddContributionTransaction" asp-route-id="@Model.Event.EventId" asp-page-handler="ToFriend">
                        <i class="fa fa-wallet"></i> Lend money
                    </a>
                </div>
            </div>
        </div>
           






        </div>


    </div>


    <div class="container friendsContainer">
        <div class="row">
            <div class="col-6 tileFooter">
                <a asp-page="/app/events/EventSettlement" asp-route-id="@Model.Event.EventId">
                    <i class="fa fa-handshake"></i> Let's Settle
                </a>
            </div>
            @if (Model.IsLoggedInUserTheEventAdmin)
            {


                <div class="col-6 tileFooter">
                    <div>
                        
                            <a asp-page="EventFriends" asp-route-id="@Model.Event.EventId">
                                <i class="fa fa-plus-square"></i> Invite Friends
                            </a>
                        
                    </div>
                </div>

            }
        </div>

        <div class="row" style="margin-top:5px">

            <div class="card-columns">
                @*for loop starts here*@
                @foreach (var friend in Model.Event.Friends.Where(f => f.IsFriendActive == true))
                {
                    <div class="card">
                        <div class="row no-gutters">
                            <div class="col-2">
                                <div>
                                    <img class="friendImage" src="@friend.Avatar.AvatarImagePath" alt="Avatar" asp-append-version="true">
                                </div>

                            </div>
                            <div class="col-10">
                                <div class="card-body">
                                    <div><p>@friend.Name</p></div>
                                    <div><p>@friend.Email</p></div>
                                    <div><p>@friend.Status</p></div>
                                </div>
                            </div>
                        </div>
                    </div>
                }

            </div>
        </div>


        </div>


        @section Scripts{

            <script src="~/js/Dashboard.js" asp-append-version="true"></script>

        }

Hisab.UI/Pages/App/Events/EventSettings.cshtml
@page "/app/events/{id}/settings"
@model Hisab.UI.EventSettingsModel
@{
    ViewData["Title"] = "EventSettings";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}



<div class="container">
    
    <div class="row">
        <div class="col-md-6 col-12 col-xs-12 ">
            <div class="card settingsCard">
                <form asp-page-handler="EventSettings" method="post">
                    @if (!ModelState.IsValid)
                    {
                        @Html.ValidationSummary(true, "", new { @class = "alert alert-danger" })
                    }

                    @Html.HiddenFor(Model => Model.SettingsVM.EventId)
                    <div class="card-header bg-warning">Event Settings</div>
                    <div class="card-body">
                        @if (!String.IsNullOrEmpty(Model.EventSettingMessage))
                        {
                            <div class="alert alert-success" role="alert">
                                @Model.EventSettingMessage
                            </div>
                        }


                        <div class="form-group row">
                            <label class="col-sm-4 col-form-label">Event Name:</label>
                            <input asp-for="@Model.SettingsVM.EventName" class="form-control col-sm-6" type="text" />

                        </div>

                        <div class="form-group row ">
                            <label for="expenseDate" class="col-sm-4 col-form-label">Currency:</label>
                            
                            @*<div class="col-sm-6">*@
                            <select id="currencySelect" class="form-control col-sm-6" asp-for="@Model.SettingsVM.SelectedCurrency" asp-items="@(new SelectList(Model.SettingsVM.CountryCurrency,"Code","Name"))">
                            </select>
                            @*</div>*@
                        </div>

                        <div class="form-group row">
                            <label class="col-sm-4 col-form-label">Choose Event Image:</label>
                                @Html.HiddenFor(Model => Model.SettingsVM.SelectedEventImage)
                            <div class="col-sm-6">
                                <div class="customCombobox" id="customCombobox1">
                                    <div id="comboSelection"></div>
                                </div>
                                <ul class="ulcustomCombobox" id="ulcustomCombobox1">
                                    @foreach (var avatar in Model.SettingsVM.EventImages)
                                    {
                                        <li id="@Convert.ToInt32(avatar.Id)">
                                            <a>
                                                <img src="@avatar.ImagePath" class="imgDisplay" asp-append-version="true" />
                                                <p class="imageText">@avatar.ImageName</p>
                                            </a>
                                        </li>
                                    }

                                </ul>
                            </div>
                         </div>

                        @if (Model.SettingsVM.Friends.Count > 0)
                        {
                            <div class="alert alert-warning" role="alert">
                                You can make a friend inative for this event. Please note, an inactive friend will still be able to
                                acess the event. However, in future transaction split an inactive friend will not be available.
                            </div>
                        }


                        @for (var i = 0; i < Model.SettingsVM.Friends.Count(); i++)
                        {


                            <div class="row" style="margin:2px;">

                                <div class="col-md-8 col-8">
                                    <label>
                                        @Model.SettingsVM.Friends[i].Name
                                        (@Model.SettingsVM.Friends[i].Status)
                                    </label>

                                    @Html.HiddenFor(x => x.SettingsVM.Friends[i].Name)
                                    @Html.HiddenFor(x => x.SettingsVM.Friends[i].UserId)
                                    @Html.HiddenFor(x => x.SettingsVM.Friends[i].EventId)
                                    @Html.HiddenFor(x => x.SettingsVM.Friends[i].Email)
                                    @Html.HiddenFor(x => x.SettingsVM.Friends[i].EventFriendStatus)
                                    @Html.HiddenFor(x => x.SettingsVM.Friends[i].Status)
                                </div>

                                <div class="col-md-4 col-4">
                                    <label class="switch">
                                        @if (Model.SettingsVM.Friends[i].EventFriendStatus == Hisab.Common.BO.EventFriendStatus.EventAdmin)
                                        {
                                            <input type="checkbox" asp-for="@Model.SettingsVM.Friends[i].IsFriendActive" disabled>
                                        }
                                        else
                                        {
                                            <input type="checkbox" asp-for="@Model.SettingsVM.Friends[i].IsFriendActive">
                                        }

                                        <span class="slider round"></span>
                                    </label>

                                </div>
                            </div>




                        }





                    </div>

                    <div class="card-footer bg-warning">
                        <button class="btn btn-primary footerButtons">Save</button>

                        <div class="clearfix"></div>
                    </div>
                </form>
            </div>
        </div>

        <div class="col-md-6 col-12 col-xs-12 ">
            <div class="card settingsCard">
                <form asp-page-handler="ArchieveEvent" method="post">
                    @Html.HiddenFor(Model => Model.SettingsVM.EventId)
                    <div class="card-header bg-warning">Archive Event</div>
                    <div class="card-body">

                        <p>
                            DANGER !! Please note, you will not be able to access the Event anymore.
                        </p>


                        <div class="form-group">
                            <button class="btn btn-danger">Archive Event</button>
                        </div>

                    </div>

                    <div class="card-footer bg-warning">


                    </div>
                </form>
            </div>
        </div>
    </div>



</div>


@section scripts{
   

    <script src="~/js/EventSettings.js" asp-append-version="true"></script>

}