Hisab.UI/Pages/App/AccessDenied.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Hisab.UI.Pages.App
{
    public class AccessDeniedModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

Hisab.UI/Pages/App/Contact.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Hisab.BL;
using Hisab.Common.BO;
using Hisab.Dapper.Identity;
using Hisab.UI.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Hisab.UI
{
    [Authorize(Roles = "App User, Admin")]
    public class ContactModel : PageModel
    {
        [BindProperty]
        public FeedbackVm FeedbackVm { get; set; }

        public string SucessMessage { get; set; }

        private UserManager<ApplicationUser> _userManager { get; set; }
        private IFeedbackManager _feedbackManager { get; set; }

        public ContactModel(UserManager<ApplicationUser> userManager, IFeedbackManager feedbackManager)
        {
            _userManager = userManager;
            _feedbackManager = feedbackManager;
        }
        public async Task<IActionResult> OnGet()
        {

            FeedbackVm = new FeedbackVm();

            return Page();

        }

        public async Task<IActionResult> OnPost()
        {
            if(ModelState.IsValid)
            {
                var user = await _userManager.FindByNameAsync(User.Identity.Name);



                var feedback = new NewFeedbackBO
                {
                    Message = FeedbackVm.Message,
                    UserId = user.Id,
                    FeedbackType = FeedbackVm.Feedback
                };

                var result = await _feedbackManager.CreateNewFeedback(feedback);

                if(result)
                {
                    ModelState.Clear();
                    SucessMessage = "Thank you for providing feedback.";
                }
            }
            

            return Page();

        }
    }
}

Hisab.UI/Pages/App/Events.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Hisab.BL;
using Hisab.Common.BO;
using Hisab.Dapper.Identity;
using Hisab.UI.Services;
using Hisab.UI.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.ViewFeatures;

namespace Hisab.UI
{
    [Authorize(Roles ="App User, Admin")]
    public class EventsModel : PageModel
    {
        public List<EventCardVm> Events { get; set; }

        [BindProperty]
        public NewEventVm NewEvent { get; set; }

        private IEventManager _eventManager;
        private UserManager<ApplicationUser> _userManager;



        public EventsModel(IEventManager eventManager, UserManager<ApplicationUser> userManager )
        {
            _eventManager = eventManager;
            _userManager = userManager;
            NewEvent = new NewEventVm();
        }
        

        public async Task<IActionResult> OnGet()
        {

            var user = await _userManager.FindByNameAsync(User.Identity.Name);
            var events = await _eventManager.GetEvents(user.Id);

            Events = new List<EventCardVm>();

            foreach (var eventBo in events.Where(e => e.EventStatus == EventStatus.Active))
            {
                Events.Add(new EventCardVm()
                {
                    EventId = eventBo.Id,
                    EventName = eventBo.EventName,
                    CurrencySymbol = Currency.GetCurrencySymbolFromCode(eventBo.CurrencyCode),
                    CreatedUserNickName = eventBo.OwnerName,
                    EventMessage = "Event Created by: " + eventBo.OwnerName,
                    EventImagePath = HisabImageManager.GetEventImages()
                                    .Where<HisabImage>(x => x.Id == eventBo.EventPic).FirstOrDefault().ImagePath
                });
            }

            foreach(var cur in Currency.GetAll())
            {
                NewEvent.CountryCurrency.Add(new CurrencyVM() { Code = cur.Key, Name = cur.Value });
            }
            return Page();
        }

        //public PartialViewResult OnGetEventModalLoad()
        //{
        //    NewEvent = new NewEventVm();

        //    return new PartialViewResult
        //    {
        //        ViewName = "_EventModal",
        //        ViewData = new ViewDataDictionary<NewEventVm>(ViewData, NewEvent)
        //    };
        //}

        public async Task<IActionResult> OnPostCreateEvent()
        {
            if(ModelState.IsValid)
            {
                var user = await _userManager.FindByNameAsync(User.Identity.Name);
                

                if (user != null)
                {
                    var eventBo = new NewEventBO()
                    {
                        EventName = NewEvent.EventName,
                        EventOwner = new NewEventFriendBO()
                        {
                            UserId = user.Id,
                            Status = EventFriendStatus.EventAdmin

                        },
                        EventPic = HisabImageManager.GetRandomEventImage(),
                        CurrencyCode = NewEvent.SelectedCurrency
                    };

                    var eventId = await _eventManager.CreateEvent(eventBo);
                    NewEvent.Url = Url.Page("/App/Events/Dashboard", new { id = eventId });
                    
                    return new RedirectResult(NewEvent.Url);
                }
            }

            var jsonObject = new { errorMessage = "Invalid data. Please provide Event Name." };

            return new JsonResult(jsonObject);
            
        }
    }
}

Hisab.UI/Pages/App/Events/AddContributionTransaction.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Hisab.BL;
using Hisab.Common.BO;
using Hisab.Dapper.Identity;
using Hisab.UI.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using NToastNotify;

namespace Hisab.UI
{
    [Authorize(Roles = "App User, Admin")]
    public class AddContributionTransactionModel : PageModel
    {
        private IEventManager _eventManager;
        private UserManager<ApplicationUser> _userManager;
        private IEventTransactionManager _transactionManager;
        //private IToastNotification _toastNotification;

        [BindProperty]
        public ContributeVM ContributeVM { get; set; }

        public AddContributionTransactionModel(IEventManager eventManager, UserManager<ApplicationUser> userManager
                , IEventTransactionManager transactionManager)
        {
            _eventManager = eventManager;
            _userManager = userManager;
            _transactionManager = transactionManager;
            //_toastNotification = toastNotification;


        }
        public void OnGet(Guid Id)
        {
            

            
        }

        public async Task<IActionResult> OnGetToFriend(Guid Id)
        {
            ContributeVM = new ContributeVM();


                var user = await _userManager.FindByNameAsync(User.Identity.Name);
                var eve = await _eventManager.GetEventById(Id);

                ContributeVM.NickName = user.NickName;
                ContributeVM.UserId = user.Id;
                ContributeVM.TransactionDate = DateTime.Now;
                ContributeVM.EventId = Id;

                foreach(var friend in eve.Friends)
                {
                    if(friend.UserId != user.Id)
                    {
                        ContributeVM.Friends.Add(new EventFriendVm()
                        {
                            UserId = friend.UserId,
                            Name = friend.NickName

                        });
                    }
                }

            this.ViewData.Add("EventTitle", eve.EventName);

            return Page();
        }

        public async Task<IActionResult> OnPost()
        {
            
            if(!ModelState.IsValid)
            {
                return Page();
            }
            
            var newTrans = new NewTransactionBO();

            

            if(ContributeVM.PaidToFriendUserId != null)
            {
                // Contribute to Friend
                newTrans.EventId = ContributeVM.EventId;
                newTrans.CreatedByUserId = ContributeVM.UserId;
                newTrans.PaidByUserId = ContributeVM.UserId;
                newTrans.TotalAmount = ContributeVM.Amount;
                newTrans.TransactionDate = ContributeVM.TransactionDate;
                newTrans.Description = ContributeVM.Description;
                newTrans.PaidToFriendUserId = ContributeVM.PaidToFriendUserId.Value;

                var result = await _transactionManager.CreateContributeToFriend(newTrans);
                if (result)
                {
                    //_toastNotification.AddSuccessToastMessage($"The Amount of {ContributeVM.Amount} is lent to your friend.");

                    return RedirectToPage("Dashboard", new { id = ContributeVM.EventId });
                }
            }

            return Page();
        }
    }
}

Hisab.UI/Pages/App/Events/TransactionDetails.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Hisab.UI
{
    public class TransactionDetailsModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

Hisab.UI/Pages/App/Friends.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Hisab.UI
{
    public class FriendsModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

Hisab.UI/Pages/App/Invites.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Hisab.BL;
using Hisab.Common.BO;
using Hisab.Dapper.Identity;
using Hisab.UI.Services;
using Hisab.UI.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Hisab.UI
{
    [Authorize(Roles = "App User, Admin")]
    public class InvitesModel : PageModel
    {
        [BindProperty]
        public List<EventCardVm> Events { get; set; }

        private IEventInviteManager _eventInviteManager;
        private UserManager<ApplicationUser> _userManager;

        public string InviteSuccessMessage { get; set; }

        public string InviteErrorMessage { get; set; }

        public InvitesModel(IEventInviteManager eventInviteManager, UserManager<ApplicationUser> userManager)
        {
            _eventInviteManager = eventInviteManager;
            _userManager = userManager;

            Events = new List<EventCardVm>();
        }
        
        public async Task<IActionResult> OnGet()
        {
            await LoadInvites();

            return Page();
        }

        private async Task LoadInvites()
        {
            var user = await _userManager.FindByNameAsync(User.Identity.Name);

            var invites = await _eventInviteManager.GetUserInvites(user.Id);

            foreach (var inviteBo in invites)
            {
                Events.Add(new EventCardVm()
                {
                    EventId = inviteBo.EventId,
                    EventName = inviteBo.EventName,
                    CreatedUserNickName = inviteBo.EventOwnerName,
                    EventMessage = "Event Created by: " + inviteBo.EventOwnerName,
                    EventImagePath = HisabImageManager.GetEventImages()
                                    .Where<HisabImage>(x => x.Id == inviteBo.EventPic).FirstOrDefault().ImagePath
                });
            }
        }

        public async Task<IActionResult> OnPostInviteDelete(Guid EventId)
        {
            var user = await _userManager.FindByNameAsync(User.Identity.Name);

            var result = await _eventInviteManager.DeleteInvite(EventId, user.Id);

            if(result)
            {
                InviteSuccessMessage = "Sucessfully deleted the invite.";
                await LoadInvites();
            }

            return Page();
        }

        public async Task<IActionResult> OnPostInviteJoin(Guid EventId)
        {
            var user = await _userManager.FindByNameAsync(User.Identity.Name);

            var result = await _eventInviteManager.JoinInvite(EventId, user.Id);

            if(result.Success)
            {
                InviteSuccessMessage = result.Messge;
            }
            else
            {
                InviteErrorMessage =  result.Messge;
            }

            await LoadInvites();
            return Page();
        }
    }
}

Hisab.UI/Pages/App/UserSettings.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Hisab.BL;
using Hisab.Common.BO;
using Hisab.Dapper.Identity;
using Hisab.UI.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Hisab.UI
{
    [Authorize(Roles = "App User, Admin")]
    public class UserSettingsModel : PageModel
    {
        [BindProperty(SupportsGet = true)]
        public UserSettingsVm UserSettingsVm { get; set; }


        [BindProperty]
        public ChangePasswordVm PasswordVm { get; set; }

        public string UserSettingsMessage { get; set; }

        private IUserSettingManager _userSettingManager;
        private UserManager<ApplicationUser> _userManager;
        private SignInManager<ApplicationUser> _signInManager;

        public UserSettingsModel(IUserSettingManager UserSettingManager,
                UserManager<ApplicationUser> userManager,
                SignInManager<ApplicationUser> signInManager)
        {
            _userSettingManager = UserSettingManager;

            _userManager = userManager;
            _signInManager = signInManager;

            UserSettingsVm = new UserSettingsVm();
            PasswordVm = new ChangePasswordVm();
        }
        public async Task<IActionResult> OnGet()
        {
            UserSettingsBO user = null;
            if (User.Identity.IsAuthenticated)
            {
                user = await _userSettingManager.GetUserSettings(User.Identity.Name);
            }

            UserSettingsVm.UserName = user.NickName;
            UserSettingsVm.SelectedAvatarId = (int)user.Avatar;

            return Page();
        }

        public async Task<IActionResult> OnPostUserSettings()
        {

            if (ModelState.IsValid)
            {

                var user = await _userManager.FindByNameAsync(User.Identity.Name);
                var result = await _userSettingManager.UpdateUserSettings(UserSettingsVm.UserName, user.Id, (AvatarEnum)UserSettingsVm.SelectedAvatarId);

                if (result)
                {
                    UserSettingsMessage = "Settings updated sucessfully";
                }
                else
                {
                    ModelState.AddModelError("", "Error updating user settings");
                }

            }


            return Page();
        }

        public async Task<IActionResult> OnPostUpdatePassword()
        {
            if (!String.IsNullOrEmpty(PasswordVm.NewPassword))
            {
                var user = await _userManager.FindByNameAsync(User.Identity.Name);
                var token = await _userManager.GeneratePasswordResetTokenAsync(user);

                var result = await _userManager.ResetPasswordAsync(user, token, PasswordVm.NewPassword);

                if (result.Succeeded)
                {
                    await _signInManager.SignOutAsync();
                    return RedirectToPage("/LoginPage");
                }
                else
                {
                    AddErrors(result);
                }
            }
            else
            {
                ModelState.AddModelError("", "You must provide a password");
            }


            return Page();
        }

        private void AddErrors(IdentityResult result)
        {
            foreach (var error in result.Errors)
            {
                ModelState.AddModelError(string.Empty, error.Description);

            }
        }
    }
}

Hisab.UI/Pages/App/AccessDenied.cshtml
@page
@model Hisab.UI.Pages.App.AccessDeniedModel
@{
    ViewData["Title"] = "AccessDenied";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

    <div class="onlyContent">
        <img style="width:100%" asp-append-version="true" src="~/img/accessDeny.png" />
    </div>

Hisab.UI/Pages/App/Contact.cshtml
@page
@model Hisab.UI.ContactModel
@{
    ViewData["Title"] = "Contact";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}


<div class="container loginForm">


    <form method="post">
        @if (!String.IsNullOrEmpty(Model.SucessMessage))
        {
            <div class="alert alert-success" role="alert">
                @Model.SucessMessage
            </div>
        }
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label>Feedback Type:</label>
                    <select asp-for="@Model.FeedbackVm.Feedback" asp-items="@Model.FeedbackVm.FeedbackList"></select>

                </div>
                <div class="form-group">
                    <textarea asp-for="@Model.FeedbackVm.Message" class="form-control" placeholder="Your Message *" style="width: 100%; height: 150px;"></textarea>
                </div>

                <div class="form-group">
                    <button>Send Message</button>
                </div>
            </div>
            <div class="col-md-6">

            </div>
        </div>
    </form>
</div>

@section scripts{
    <script src="~/node_modules/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/node_modules/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.min.js"></script>

}

Hisab.UI/Pages/App/Events.cshtml
@page "/App/Events"

@model Hisab.UI.EventsModel
@{
    ViewData["Title"] = "Events";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}


<!-- Button trigger modal -->
<button type="button" id="eventModalButton" class="pageButton" data-toggle="modal" data-target="#newEventModal">
    Create New Event
</button>

<div class="clearfix"></div>

<div id="eventModalPlaceHolder">
    <partial name="_EventModal" model="@Model.NewEvent" />

</div>




<div class="container">
    

        @if (Model.Events.Count > 0)
        {
            <div class="card-columns">
                @foreach (var hisabEvent in Model.Events)
                {

                    <vc:event-card event-card-vm="@hisabEvent"></vc:event-card>


                }
            </div>
        }
        else
        {
            <div class="stitched">
                            	
                <p>Welcome to Hisab !! Let's get you started &#128522</p>

                <p>Create your first event &#9971 by clicking "Create New Event" button at the top &#11014 </p>

                <p>Or Check your invites &#128140 to join any events created by your friends. </p>

            </div>
        }



   
</div>

@section scripts{

    <script src="~/js/apphome.js" asp-append-version="true"></script>

    <script>
        $(document).ready(function () {
            var getModal = "@Url.Page("/App/Events",pageHandler: "EventModalLoad")";
            var postUrl =  "@Url.Page("/App/Events",pageHandler: "CreateEvent")";
            var page = new HomePage(getModal, postUrl);
            page.Init();


        });
    </script>

}

Hisab.UI/Pages/App/Invites.cshtml
@page
@model Hisab.UI.InvitesModel
@{
    ViewData["Title"] = "Invites";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}


    <div class="container">

        @if (!String.IsNullOrEmpty(Model.InviteSuccessMessage))
        {
            <div class="alert alert-success" role="alert">
                @Model.InviteSuccessMessage
            </div>
        }
        @if (!String.IsNullOrEmpty(Model.InviteErrorMessage))
        {
            <div class="alert alert-success" role="alert">
                @Model.InviteErrorMessage
            </div>
        }

        @if (Model.Events.Count > 0)
        {
            <div class="card-columns">
                @for (var i = 0; i < Model.Events.Count; i++)
                {

                    <div class="card">
                        <div class="row no-gutters">
                            <div class="col-5">
                                <img style="width:100%; height:100%" src="@Model.Events[i].EventImagePath" alt="Card image cap" asp-append-version="true">
                            </div>
                            <div class="col-7">
                                <div class="card-body">
                                    <h5 class="card-title"> @Model.Events[i].EventName</h5>
                                    <p class="card-text">
                                        @Model.Events[i].EventMessage
                                    </p>

                                </div>

                            </div>

                        </div>
                        <div class="row no-gutters">

                            <div class="col-5">
                                <form id="@Model.Events[i].EventId" asp-page-handler="InviteDelete" asp-route-EventId="@Model.Events[i].EventId">
                                    <button class="btn btn-outline-danger">Delete</button>
                                </form>



                            </div>
                            <div class="col-7" style="text-align:right">
                                <form id="@Model.Events[i].EventId" asp-page-handler="InviteJoin" asp-route-EventId="@Model.Events[i].EventId">
                                    <button class="btn btn-outline-primary">Join</button>
                                </form>



                            </div>

                        </div>
                    </div>


                }
            </div>
        }
        else
        {
            <div class="stitched">

                <p>Hey !! you don't have any invites &#128140 </p>

            </div>
        }




    </div>

Hisab.UI/Pages/App/UserSettings.cshtml
@page
@model Hisab.UI.UserSettingsModel
@using Hisab.UI.Extensions
@{
    ViewData["Title"] = "UserSettings";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}


    <div class="container">
        @Html.ValidationSummary(true, "", new { @class = "alert alert-danger" })
        <div class="row">
            <div class="col-md-6 col-12 col-xs-12 ">
                <div class="card settingsCard">
                    <form asp-page-handler="UserSettings" method="post">

                        <div class="card-header bg-warning">Change User Name</div>
                        <div class="card-body">
                            @if (!String.IsNullOrEmpty(Model.UserSettingsMessage))
                            {
                                <div class="alert alert-success" role="alert">
                                    @Model.UserSettingsMessage
                                </div>
                            }
                            

                            <div class="form-group">
                                <label>Enter User Name:</label>
                                <input asp-for="@Model.UserSettingsVm.UserName" class="form-control" type="text" />
                                <span asp-validation-for="@Model.UserSettingsVm.UserName" class="text-danger"></span>
                            </div>

                            <div class="form-group">
                                <label>Choose Avatar:</label>
                                @Html.HiddenFor(Model => Model.UserSettingsVm.SelectedAvatarId)
                                <span asp-validation-for="@Model.UserSettingsVm.SelectedAvatarId" class="text-danger"></span>
                                <div class="customCombobox" id="customCombobox1">
                                    <div id="comboSelection"></div>
                                </div>
                                <ul class="ulcustomCombobox" id="ulcustomCombobox1">
                                    @foreach (var avatar in Model.UserSettingsVm.Avatars)
                                    {
                                        <li id="@Convert.ToInt32(avatar.Avatar)">
                                            <a>
                                                <img src="@avatar.AvatarImagePath" class="imgDisplay" asp-append-version="true" />
                                                <p class="imageText">@avatar.Avatar.GetDescription()</p>
                                            </a>
                                        </li>
                                    }

                                </ul>


                            </div>

                        </div>

                        <div class="card-footer bg-warning">
                            <button class="btn btn-primary footerButtons">Save</button>
                            <div class="clearfix"></div>
                        </div>
                    </form>
                </div>
            </div>

            <div class="col-md-6 col-12 col-xs-12 ">
                <div class="card settingsCard">
                    <form asp-page-handler="UpdatePassword" method="post">
                        <div class="card-header bg-warning">Change Password</div>
                        <div class="card-body">

                            <p>
                                You will be asked to login again after sucessfully updating your password.
                            </p>


                            <div class="form-group">
                                <label>Enter new Password:</label>
                                <input class="form-control" type="password" asp-for="@Model.PasswordVm.NewPassword" />
                                <span asp-validation-for="@Model.PasswordVm.NewPassword" class="text-danger"></span>
                            </div>

                        </div>

                        <div class="card-footer bg-warning">
                            <button class="btn btn-primary footerButtons">Save</button>
                            <div class="clearfix"></div>
                        </div>
                    </form>
                </div>
            </div>
        </div>



    </div>

@section scripts{
    <script src="~/node_modules/jquery-validation/dist/jquery.validate.min.js" asp-append-version="true"></script>
    <script src="~/node_modules/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.min.js" asp-append-version="true"></script>

    <script src="~/js/UserSettings.js" asp-append-version="true"></script>

}